version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 8880:15672
    volumes:
        - ./data/rabbitmq/data/:/var/lib/rabbitmq/
        - ./data/rabbitmq/log/:/var/log/rabbitmq

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./data/postgresql/data:/var/lib/postgresql/data
      - ./data/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8881:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@docker.local
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
