version: "3.8"

services:
  rabbitmq:
    extends:
      file: docker-compose.core.yml
      service: rabbitmq

  postgres:
    extends:
      file: docker-compose.core.yml
      service: postgres

  data-store:
    image: demo-data-store:main
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - NODE_ENV=production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  api-gateway:
    image: demo-api-gateway:main
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - NODE_ENV=production
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
