version: "3.8"

include:
  - docker-compose.core.yml

services:
  todos-datastore:
    image: todos-datastore:main
    container_name: todos-datastore
    depends_on:
      - rabbitmq
      - postgres
    environment:
     - NODE_ENV=development
     - PORT=3000
     - DATABASE_HOST=postgres
     - DATABASE_PORT=5432
     - DATABASE_USERNAME=postgres
     - DATABASE_PASSWORD=postgres
     - DATABASE_NAME=todos_datastore
     - BROKER_SERVICE=todos-datastore
     - BROKER_URL=amqp://guest:guest@rabbitmq:5672
     - BROKER_QUEUE_COMMANDS_NAME=todos-commands
     - BROKER_QUEUE_EVENTS_NAME=todos-events
    networks:
      - core

  todos-api:
    image: todos-api:main
    container_name: todos-api
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - postgres
    environment:
     - NODE_ENV=development
     - PORT=3000
     - DATABASE_HOST=postgres
     - DATABASE_PORT=5432
     - DATABASE_USERNAME=postgres
     - DATABASE_PASSWORD=postgres
     - DATABASE_NAME=todos_api
     - BROKER_SERVICE=todos-api
     - BROKER_URL=amqp://guest:guest@rabbitmq:5672
     - BROKER_QUEUE_COMMANDS_NAME=todos-commands
     - BROKER_QUEUE_EVENTS_NAME=todos-events
    networks:
      - core
